name: GP PR Builder
on:
  pull_request:
    branches: [ develop_front, main ]
defaults:
  run:
    shell: bash
    working-directory: .
jobs:
  build:
    name: PR Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > app/google-services.json

      - name: Access EXIT_BASE_URL
        env:
          EXIT_BASE_URL: ${{ secrets.EXIT_BASE_URL }}
        run: echo "EXIT_BASE_URL=\"$EXIT_BASE_URL\"" >> local.properties

      - name: Touch local properties
        run: touch local.properties

      - name: Lint Check
        run: ./gradlew ktlintCheck

      - name: Build with Gradle
        run: ./gradlew build
